/* Generated by cbindgen — do not edit manually. */

#ifndef OXBITNET_H
#define OXBITNET_H

/* Warning: this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stddef.h>

/**
 * Load progress phase.
 */
typedef enum OxBitNetLoadPhase {
  Download = 0,
  Parse = 1,
  Upload = 2,
} OxBitNetLoadPhase;

/**
 * Opaque handle to a loaded BitNet model.
 */
typedef struct OxBitNet OxBitNet;

/**
 * Options for text generation.
 */
typedef struct OxBitNetGenerateOptions {
  /**
   * Maximum number of tokens to generate.
   */
  uintptr_t max_tokens;
  /**
   * Sampling temperature.
   */
  float temperature;
  /**
   * Top-k sampling parameter.
   */
  uintptr_t top_k;
  /**
   * Repetition penalty.
   */
  float repeat_penalty;
  /**
   * Window size for repetition penalty.
   */
  uintptr_t repeat_last_n;
} OxBitNetGenerateOptions;

/**
 * Progress information passed to the load progress callback.
 */
typedef struct OxBitNetLoadProgress {
  enum OxBitNetLoadPhase phase;
  uint64_t loaded;
  uint64_t total;
  double fraction;
} OxBitNetLoadProgress;

/**
 * Progress callback type. Called during model loading.
 */
typedef void (*OxBitNetProgressFn)(const struct OxBitNetLoadProgress *progress, void *userdata);

/**
 * Options for loading a model.
 */
typedef struct OxBitNetLoadOptions {
  /**
   * Progress callback (nullable).
   */
  OxBitNetProgressFn on_progress;
  /**
   * User data passed to the progress callback (nullable).
   */
  void *progress_userdata;
  /**
   * Cache directory path, null-terminated UTF-8 (nullable).
   */
  const char *cache_dir;
} OxBitNetLoadOptions;

/**
 * Token callback type. Return 0 to continue, non-zero to stop.
 */
typedef int32_t (*OxBitNetTokenFn)(const char *token, uintptr_t len, void *userdata);

/**
 * A chat message with role and content.
 */
typedef struct OxBitNetChatMessage {
  /**
   * Role string, null-terminated UTF-8 (e.g. "user", "assistant", "system").
   */
  const char *role;
  /**
   * Content string, null-terminated UTF-8.
   */
  const char *content;
} OxBitNetChatMessage;

/**
 * Return default generation options.
 */
struct OxBitNetGenerateOptions oxbitnet_default_generate_options(void);

/**
 * Return default load options (no progress callback, no cache dir).
 */
struct OxBitNetLoadOptions oxbitnet_default_load_options(void);

/**
 * Load a BitNet model from a URL or local file path.
 *
 * `source` must be a null-terminated UTF-8 string.
 * `options` may be NULL for defaults.
 *
 * Returns an opaque handle on success, or NULL on error.
 * On error, call `oxbitnet_error_message()` for details.
 *
 * # Safety
 *
 * - `source` must be a valid null-terminated UTF-8 string.
 * - `options`, if non-null, must point to a valid `OxBitNetLoadOptions`.
 */
struct OxBitNet *oxbitnet_load(const char *source, const struct OxBitNetLoadOptions *options);

/**
 * Free a model handle and release all GPU resources.
 *
 * Passing NULL is a no-op.
 *
 * # Safety
 *
 * - `model` must be NULL or a pointer previously returned by `oxbitnet_load`
 *   that has not yet been freed.
 */
void oxbitnet_free(struct OxBitNet *model);

/**
 * Generate text from a raw prompt string.
 *
 * Tokens are delivered via `callback`. Return 0 from the callback to continue,
 * non-zero to stop early.
 *
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * - `model` must be a valid pointer from `oxbitnet_load`.
 * - `prompt` must be a valid null-terminated UTF-8 string.
 * - `options` may be NULL for defaults.
 * - `callback` must be a valid function pointer or NULL (NULL = generate silently).
 */
int32_t oxbitnet_generate(struct OxBitNet *model,
                          const char *prompt,
                          const struct OxBitNetGenerateOptions *options,
                          OxBitNetTokenFn callback,
                          void *userdata);

/**
 * Generate text from chat messages.
 *
 * Tokens are delivered via `callback`. Return 0 from the callback to continue,
 * non-zero to stop early.
 *
 * Returns 0 on success, -1 on error.
 *
 * # Safety
 *
 * - `model` must be a valid pointer from `oxbitnet_load`.
 * - `messages` must point to `num_messages` valid `OxBitNetChatMessage` structs.
 * - `options` may be NULL for defaults.
 * - `callback` must be a valid function pointer or NULL.
 */
int32_t oxbitnet_chat(struct OxBitNet *model,
                      const struct OxBitNetChatMessage *messages,
                      uintptr_t num_messages,
                      const struct OxBitNetGenerateOptions *options,
                      OxBitNetTokenFn callback,
                      void *userdata);

/**
 * Get the last error message, or NULL if no error occurred.
 *
 * The returned pointer is owned by the library and valid until the next
 * FFI call on the same thread.
 */
const char *oxbitnet_error_message(void);

#endif  /* OXBITNET_H */
